spring: 
  datasource:
    url: jdbc:mysql://192.168.83.84:3308/akworksche_dev?useUnicode=true&characterEncoding=utf-8
    username: akjfdev
    password: sajkf898
    driver-class-name: org.mariadb.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  
server:
  port: 8081
  session:
    timeout: 1800
    
logging:
    level:
        tk.mybatis: TRACE   
mapper:
    mappers:
        - com.akcomejf.worksche.utils.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql